### ISSUE TITLE
Change to the Merchant Card on Home Screen

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Native---Android#12]
Removed

**Comment by ptxd** [comment]
Store: Pull from API
Expiry: mm-dd-yy
Status: Active (hard code)
Pool : <amount> (pull from API)

**Comment by vishal-vpb** [comment]
@ptxd - Resolved in Android and same is pushed to branch "Feature/BugFixing" along with other fixed bugs.
PS - I have used the expiry date format as given above. i.e. mm-dd-yy.

**Comment by ptxd** [comment]
Tested and closed
