### ISSUE TITLE
App does not refresh after database updates

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Native---Android#20]
The state persists in the header as the user moves along the tab bar if the database is updated the user does not receive the update until the app is restarted.

Fix Recommendation:

1. When the user pulls the page down, refresh the page (all API points)
2. Every time user switches between header make API call for total cashback and level

**Comment by vishal-vpb** [comment]
Resolved - As discussed
1) after pulling down gesture - top panel (cashback and xp points) and deals both should get updated.
2) on switching using bottom menu - only deals should be refresh.
