### ISSUE TITLE
List of Banks

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Native---Android#22]
Wells Fargo
BankofAmerica
JPMorgan Chase
U.S. Bank
MUFG Union Bank
Citibank
Bank of the West
Rabobank
Comerica Bank
ZB
First Bank
CIT Bank
Pacific Western Bank
Others: < Allow Manual Input By User >

**Comment by vishal-vpb** [comment]
@ptxd -1)  Bank list needs to be added by admin or backend (I have asked the team to remove the same from backend) You can expect to review the result in build version 1.0.0.8)
2) Regarding adding bank name manually we will discuss the same over call.
