### ISSUE TITLE
Redeem Mode Requirements

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Native---Android#23]
### **Bank Account**

Requires: 
1. Name of bank
2. Account Number
3. Routing Number
4. Amount ( Allow 2 decimal points + validation checks)

### **Cryptocurrencies**

Requires:
1. List:
Bitcoin
BitcoinCash
Ethereum
Stellar
EOS

2. Wallet Address
3. Amount ( Allow 2 decimal points + validation checks)

### **Cheque**

Requires 
1. Name
2. Address
3. Amount ( Allow 2 decimal points + validation checks)

Remove Post -- Bug

**Comment by vishal-vpb** [comment]
@Ptxd 1) Resolved for Routing number
2) Other changes like Cryptocurrency list and removing "Post" needs to be done by admin or backend (I have asked the team to remove the same from backend) You can expect to review the result in build version 1.0.0.8

**Comment by ptxd** [comment]
Change Name as per bank to Name in cheque name field
